version: '3.8'

services:
  mailcatcher:
    platform: linux/x86_64
    image: dockage/mailcatcher:0.9.0
    container_name: mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge