controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Path: config/routes.yaml
app_homepage:
    path: /
    controller: App\Controller\AtelierController::index

app_questionnaire:
    path: /questionnaire
    controller: App\Controller\QuestionnaireController::fillQuestionnaire
